### ISSUE TITLE
Contributing features

### ISSUE THREAD

**Issue by trev-dev** [djhouseknecht/rollup-plugin-version-injector#85]
Hey @djhouseknecht!

I noticed that this project is based on the now unmaintained webpack-auto-inject-version. I had used the same plugin as inspiration to write my own webpack 5 compliant version: https://github.com/trev-dev/webpack-plugin-log-version

I'm new to rollup, but I like it! I was wondering if you'd be interested in receiving some pull requests related to some of the features I wrote. Namely:
1. Git integration (show the current branch/workspace status)
2. Comment in the console as an opt-in option for this project
3. An optional window global for quickly (but quietly) referencing the recent build without looking at the source.

If you're open to these features I'd be happy to do the work.

**Comment by djhouseknecht** [comment]
Hey @trev-dev, I would totally be up for those new features! They sound really helpful. The one feature that I didn't like in the original AIV was the auto version bumping, but the ones you listed sound great. I'd gladly take a look at PRs and get those merged in. I'll take a look at your repo too because I have some webpack apps still using AIV.

**Comment by trev-dev** [comment]
Awesome. I'll set some free time aside and play.

**Comment by trev-dev** [comment]
Finally finding a few minutes to breathe here and assess where to write with a little free time :) I'll see about getting a PR this week.
